GET https://api.themoviedb.org/3/movie/popular HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJmNjU0YzkzZjEyNTUyMTAxYTQwM2YyODJhYzEzZWY5MCIsInN1YiI6IjY1YWJlZGU5YjFmNjhkMDE3MGViZTQ5OCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.538jieiqBD2OaD3pA8-JVpEBeojhiWIG3cMIWRQA9zg

###
GET https://api.themoviedb.org/3/configuration HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJmNjU0YzkzZjEyNTUyMTAxYTQwM2YyODJhYzEzZWY5MCIsInN1YiI6IjY1YWJlZGU5YjFmNjhkMDE3MGViZTQ5OCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.538jieiqBD2OaD3pA8-JVpEBeojhiWIG3cMIWRQA9zg